FROM node:lts-alpine AS build

WORKDIR /app
COPY . /app

ARG REACT_APP_HTTP_API_URL
ENV REACT_APP_HTTP_API_URL $REACT_APP_HTTP_API_URL
ARG REACT_APP_WEBSOCKET_API_URL
ENV REACT_APP_WEBSOCKET_API_URL $REACT_APP_WEBSOCKET_API_URL
ARG REACT_APP_ENABLE_NOTIFICATION
ENV REACT_APP_ENABLE_NOTIFICATION $REACT_APP_ENABLE_NOTIFICATION
ARG REACT_APP_ENABLE_CALL_NOTIFICATION
ENV REACT_APP_ENABLE_CALL_NOTIFICATION $REACT_APP_ENABLE_CALL_NOTIFICATION
ARG EXTEND_ESLINT=true
ARG REACT_APP_REFETCH_ON_WINDOW_FOCUS=false

RUN yarn install --frozen-lockfile && yarn build

FROM nginx:stable-alpine
COPY --from=build /app/build /usr/share/nginx/html

COPY nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
