export const OPERATION_STATUS_IN_PROGRESS = 'IN_PROGRESS';
export const OPERATION_STATUS_COMPLETED = 'COMPLETED';
export const OPERATION_STATUS_CANCELED = 'CANCELED';
export const OPERATION_STATUS_WAITING = 'WAITING';

export const OPERATION_STAGE_SIMPLE = 'SIMPLE';
export const OPERATION_STAGE_OPERATION = 'OPERATION';
export const OPERATION_STAGE_INITIAL_CONSULTATION = 'INITIAL_CONSULTATION';

export const OPERATION_CREATED_STAGE_STATUS_DONE = 'DONE';
export const OPERATION_CREATED_STAGE_STATUS_CANCEL = 'CANCEL';
export const OPERATION_CREATED_STAGE_STATUS_REWORK = 'REWORK';
export const OPERATION_CREATED_STAGE_STATUS_PENDING = 'PENDING';
export const OPERATION_CREATED_STAGE_STATUS_IN_PROGRESS = 'IN_PROGRESS';
