export const STATUS_HOSPITAL_RECEPTION_CONFIRMED = 'CONFIRMED';
export const STATUS_HOSPITAL_RECEPTION_CASH = 'CASH';
export const STATUS_HOSPITAL_RECEPTION_PAID = 'PAID';
export const STATUS_HOSPITAL_RECEPTION_WAITING = 'WAITING';
