export const MONEY_ACCOUNT_TYPE_CASH = 'CASH';
export const MONEY_ACCOUNT_TYPE_NON_CASH = 'NON_CASH';

export const TYPE_CATEGORY_GLOBAL_FINANCE = 'GLOBAL_FINANCE';
export const TYPE_CATEGORY_CASH = 'CASH';
