export const WAYBILL_STATUS_PLAN = 'PLAN';
export const WAYBILL_STATUS_ACCEPTED = 'ACCEPTED';
export const WAYBILL_STATUS_COMPLETED = 'DONE';
export const WAYBILL_STATUS_CANCELED = 'CLOSED';
export const WAYBILL_STATUS_REWORK = 'REWORK';
export const WAYBILL_STATUS_CONTROL = 'CONTROL';
export const WAYBILL_STATUS_DELETED = 'DELETED';

export const WAYBILL_TYPE_ACCEPTANCE = 'ACCEPTANCE';
export const WAYBILL_TYPE_WRITE_OFF = 'WRITE_OFF';
export const WAYBILL_TYPE_EXPENSE = 'EXPENSE';
export const WAYBILL_TYPE_MOVING = 'MOVING';

export const WAYBILL_COMMENT_TYPE_SUCCESS = 'SUCCESS';
export const WAYBILL_COMMENT_TYPE_FAIL = 'FAIL';
export const WAYBILL_COMMENT_TYPE_WARNING = 'WARNING';
export const WAYBILL_COMMENT_TYPE_INFO = 'INFO';
