export const STATUS_LABORATORY_RECEPTION_CONFIRMED = 'CONFIRMED';
export const STATUS_LABORATORY_RECEPTION_CASH = 'CASH';
export const STATUS_LABORATORY_RECEPTION_PAID = 'PAID';
export const STATUS_LABORATORY_RECEPTION_WAITING = 'WAITING';
