export const STATUS_TREATMENT_WAITING = 'WAITING';
export const STATUS_TREATMENT_IN_PROGRESS = 'IN_PROGRESS';
export const STATUS_TREATMENT_COMPLETED = 'COMPLETED';
export const STATUS_TREATMENT_CANCELED = 'CANCELED';
export const STATUS_TREATMENT_NOT_STARTED = 'NOT_STARTED';
