export const TYPE_REVIEW_PATIENT = 'REVIEW_PATIENT';
export const TYPE_REVIEW_PARTNER = 'REVIEW_PARTNER';
export const TYPE_REVIEW_DOCTOR = 'REVIEW_DOCTOR';
export const TYPE_COMPLIENT_PATIENT = 'COMPLIENT_PATIENT';
export const TYPE_COMPLIENT_PARTNER = 'COMPLIENT_PARTNER';
export const TYPE_COMPLIENT_DOCTOR = 'COMPLIENT_DOCTOR';
export const TYPE_PROPOSAL_PATIENT = 'PROPOSAL_PATIENT';
export const TYPE_PROPOSAL_PARTNER = 'PROPOSAL_PARTNER';
export const TYPE_PROPOSAL_DOCTOR = 'PROPOSAL_DOCTOR';

export const STATUS_NEW = 'NEW';
export const STATUS_PROCESSING = 'PROCESSING';
export const STATUS_DONE = 'DONE';
export const STATUS_CLOSED = 'CLOSED';
