export const STATUS_RECEPTION_APPOINTED = 'APPOINTED';
export const STATUS_RECEPTION_CONFIRMED = 'CONFIRMED';
export const STATUS_RECEPTION_CASH = 'CASH';
export const STATUS_RECEPTION_PAID = 'PAID';
export const STATUS_RECEPTION_CANCEL = 'CANCEL';
export const STATUS_RECEPTION_FAILED = 'FAILED';
export const STATUS_RECEPTION_WAITING = 'WAITING';
export const STATUS_RECEPTION_NOT_PAID = 'NOT_PAID';

export const MONDAY_NAME = 'MONDAY';
export const TUESDAY_NAME = 'TUESDAY';
export const WEDNESDAY_NAME = 'WEDNESDAY';
export const THURSDAY_NAME = 'THURSDAY';
export const FRIDAY_NAME = 'FRIDAY';
export const SATURDAY_NAME = 'SATURDAY';
export const SUNDAY_NAME = 'SUNDAY';

export const RESERVE_PRIORITY_LOW = 'LOW';
export const RESERVE_PRIORITY_MEDIUM = 'MEDIUM';
export const RESERVE_PRIORITY_HIGH = 'HIGH';

export const TYPE_SERVICE_HOSPITAL = 'HOSPITAL';
export const TYPE_SERVICE_COMMON = 'COMMON';
export const TYPE_SERVICE_LABORATORY = 'LABORATORY';
export const TYPE_SERVICE_OPERATION = 'OPERATION';

export const SERVICE_PAYOUT_COUNTERPARTY_TYPE_DOCTOR = 'DOCTOR';
export const SERVICE_PAYOUT_COUNTERPARTY_TYPE_PARTNER = 'PARTNER';
export const SERVICE_PAYOUT_COUNTERPARTY_TYPE_PERSONAL = 'PERSONAL';

export const SERVICE_CALCULATION_TYPE_FULL_COST = 'FULL_COST';
export const SERVICE_CALCULATION_TYPE_WITH_EXPENSES = 'WITH_EXPENSES';

export const SERVICE_PAYOUT_STOCKTAKING_ALWAYS = 'ALWAYS';
export const SERVICE_PAYOUT_STOCKTAKING_CHOOSE = 'CHOOSE';
