export const FINANCE_STATE_TYPE_COMING = 1;
export const FINANCE_STATE_TYPE_SPENDING = 0;
export const FINANCE_STATE_TYPE_MOVING = 2;

export const COUNTERPARTY_TYPE_PATIENT = 'PATIENT';
export const COUNTERPARTY_TYPE_DOCTOR = 'DOCTOR';
export const COUNTERPARTY_TYPE_PARTNER = 'PARTNER';
export const COUNTERPARTY_TYPE_MONEY_ACCOUNT = 'MONEY_ACCOUNT';

export const FINANCE_BASE_TYPE_STATIONARY_RECEPTION = 'StationaryReception';
export const FINANCE_BASE_TYPE_LABORATORY_RECEPTION = 'LaboratoryReception';
export const FINANCE_BASE_TYPE_OPERATION = 'Operation';
export const FINANCE_BASE_TYPE_RECEPTION = 'Reception';

export const CASHIER_SHIFT_FINANCE_ACTION_TYPE_PARTNER = 'PARTNER';
export const CASHIER_SHIFT_FINANCE_ACTION_TYPE_INCOMING = 'INCOMING';
export const CASHIER_SHIFT_FINANCE_ACTION_TYPE_OUTGOING = 'OUTGOING';
export const CASHIER_SHIFT_FINANCE_ACTION_TYPE_MOVING = 'MOVING';

export const CASHIER_SHIFT_STATUS_OPEN = 'OPEN';
export const CASHIER_SHIFT_STATUS_CONTROL = 'CONTROL';
export const CASHIER_SHIFT_STATUS_REWORK = 'REWORK';
export const CASHIER_SHIFT_STATUS_CLOSED = 'CLOSED';

export const PROMOTION_TYPE_DISCOUNT = 'DISCOUNT';
export const PROMOTION_TYPE_CASHBACK = 'CASHBACK';

export const PROMOTION_STATUS_ACTIVE = 'ACTIVE';
export const PROMOTION_STATUS_COMPLETED = 'COMPLETED';
