export const EMPLOYEES_BASE_TYPE_STATIONARY_RECEPTION = 'StationaryReception';
export const EMPLOYEES_BASE_TYPE_LABORATORY_RECEPTION = 'LaboratoryReception';
export const EMPLOYEES_BASE_TYPE_RECEPTION = 'Reception';
export const EMPLOYEES_BASE_TYPE_OPERATION = 'Operation';

export const DOCTOR_WORK_SHIFT_STATUS_OPEN = 'OPEN';
export const DOCTOR_WORK_SHIFT_STATUS_WAREHOUSE_CONTROL = 'WAREHOUSE_CONTROL';
export const DOCTOR_WORK_SHIFT_STATUS_WAREHOUSE_ACCEPTED = 'WAREHOUSE_ACCEPTED';
export const DOCTOR_WORK_SHIFT_STATUS_WAREHOUSE_REWORK = 'WAREHOUSE_REWORK';
export const DOCTOR_WORK_SHIFT_STATUS_RESPONSIBLE_CONTROL = 'RESPONSIBLE_CONTROL';
export const DOCTOR_WORK_SHIFT_STATUS_RESPONSIBLE_REWORK = 'RESPONSIBLE_REWORK';
export const DOCTOR_WORK_SHIFT_STATUS_CLOSED = 'CLOSED';

export const WEEKDAYS = {
	MONDAY: 'MONDAY',
	TUESDAY: 'TUESDAY',
	WEDNESDAY: 'WEDNESDAY',
	THURSDAY: 'THURSDAY',
	FRIDAY: 'FRIDAY',
	SATURDAY: 'SATURDAY',
	SUNDAY: 'SUNDAY'
};
