export const TYPE_PRODUCT_COST_HISTORY_SALE = 'SALE';
export const TYPE_PRODUCT_COST_HISTORY_PURCHASE = 'PURCHASE';

export const PRODUCT_PROMOTION_TYPE_DISCOUNT = 'DISCOUNT';
export const PRODUCT_PROMOTION_TYPE_CASHBACK = 'CASHBACK';

export const PRODUCT_PROMOTION_STATUS_ACTIVE = 'ACTIVE';
export const PRODUCT_PROMOTION_STATUS_COMPLETED = 'COMPLETED';

export const PRODUCT_PROMOTION_STATUS_TYPE_DISABLED = 'DISABLE';
